[package]
name = "cookie-session"
version = "0.1.0"
authors = ["ohs80340"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-session = "0.4"
env_logger = "0.8"